"""add document summary

Revision ID: 1b78fbecadef
Revises: 8483b37a15dd
Create Date: 2026-08-01 15:32:52.732781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b78fbecadef'
down_revision: Union[str, Sequence[str], None] = '8483b37a15dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('mimeType', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('fileSize', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('s3Key', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('summaryStatus', sa.Enum('pending', 'processing', 'completed', 'failed', name='processingstatusenum'), nullable=False))
    op.add_column('documents', sa.Column('summaryGeneratedAt', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('documents_s3_key_key'), 'documents', type_='unique')
    op.create_unique_constraint(None, 'documents', ['s3Key'])
    op.drop_column('documents', 's3_key')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'mime_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('mime_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('s3_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='unique')
    op.create_unique_constraint(op.f('documents_s3_key_key'), 'documents', ['s3_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('documents', 'summaryGeneratedAt')
    op.drop_column('documents', 'summaryStatus')
    op.drop_column('documents', 'summary')
    op.drop_column('documents', 's3Key')
    op.drop_column('documents', 'fileSize')
    op.drop_column('documents', 'mimeType')
    # ### end Alembic commands ###
