"""rename last_summarised_message_id column to camelCase

Revision ID: 4a76dfb72212
Revises: b88017823297
Create Date: 2026-06-02 15:05:10.095956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a76dfb72212'
down_revision: Union[str, Sequence[str], None] = 'b88017823297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversations_lastSummarisedMessageId_fkey'), 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'lastSummarisedMessageId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('lastSummarisedMessageId', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('conversations_lastSummarisedMessageId_fkey'), 'conversations', 'messages', ['lastSummarisedMessageId'], ['id'])
    
    # ### end Alembic commands ###
