"""update error message column

Revision ID: 7bd14efe7472
Revises: e7b29beffbac
Create Date: 2026-08-04 14:59:19.447174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd14efe7472'
down_revision: Union[str, Sequence[str], None] = 'e7b29beffbac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('errorMessage', sa.Text(), nullable=True))
    op.drop_column('documents', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('error_message', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('documents', 'errorMessage')
    # ### end Alembic commands ###
