"""add document_count to conversations

Revision ID: 8483b37a15dd
Revises: 4190ab62f507
Create Date: 2026-06-26 16:41:29.711091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8483b37a15dd'
down_revision: Union[str, Sequence[str], None] = '4190ab62f507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "conversations",
        sa.Column(
            "documentCount",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'documentCount')
    # ### end Alembic commands ###
