"""add topics field in documents

Revision ID: 8d5dfb9a2c57
Revises: 1b78fbecadef
Create Date: 2026-08-01 16:10:46.949037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d5dfb9a2c57'
down_revision: Union[str, Sequence[str], None] = '1b78fbecadef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('topics', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'topics')
    # ### end Alembic commands ###
